### ISSUE TITLE
this Action has been cancelling other actions in the same workflow

### ISSUE THREAD

**Issue by fbartho** [jessfraz/branch-cleanup-action#12]
I think Github changed something when they launched an update this week. 

This action was working great in our main workflow for a few weeks, until Monday (2019-03-12) when they launched the UI updates to indicate an Action had "Declined" to run. Then this action started terminating other things in the same workflow.

Workaround was to shift this to a different Workflow, but I'm not sure if that will scale cleanly if we add other conditional actions!

**Comment by jessfraz** [comment]
I don’t think that behavior is something I personally can fix in this repo please open an issue with github support

**Comment by fbartho** [comment]
@jessfraz if you change the exit code to be 0 then it won’t cancel. I might look at providing a PR that adds a parameter to do this, if you’re interested? 

New (to me) docs: 
https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses
