### ISSUE TITLE
Deleting the branch ref triggers delete of another PR branched off this branch

### ISSUE THREAD

**Issue by lucas-nelson** [jessfraz/branch-cleanup-action#6]
Situation:

* PR 100 sitting there with a few commits on feature/100.
* PR 101 on branch feature/101 that was branched from the HEAD of feature/100 and added a commit. The base of PR101 is set to the feature/100 branch so you can see the additional commit separately. The intention is to merge PR 100 to develop first, then change PR 101 to base: develop and review/merge PR 101 later.

PR 100 is merged and this action fires. The feature/100 branch's ref is deleted.

PR 101 gets closed as a side-effect. In PR 101, I see this in the timeline:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/5751835/51725138-d0281280-20b4-11e9-9ab2-613a99db3db4.png">

I've poked around and cannot see anything in the GitHub REST API that will tell me that there's another branch in the repo branched off this branch (or another PR based on such a branch, or another PR with this branch as a branch base). In the GitHub UI there's some detection of this situation because in the PR 100 screen, the "Delete Branch" button *does not show* while PR 101 is sitting there with `feature/100` as the base branch.

I'm not even sure there's a solution to this. Perhaps a mention in the README that it's expected behaviour?

Any other ideas?

**Comment by jessfraz** [comment]
I’m not sure there is a solution to this, maybe we should add something to the readme saying that you shouldn’t use this if there’s multiple PRs open from the same branch

**Comment by lucas-nelson** [comment]
Apologies my wording was sloppy, the second PR's head is not the first branch.

PR100 - branch: feature/one, target-for-merge: develop
PR101 - branch: feature/two, target-for-merge: feature/one

So depending on how you look at it, PR101 is not open from the "same branch", though they do share the same parentage.

Not sure if that helps or even clarifies anything.

And I should have added on the original text: thank you for authoring and sharing this action. I shamelessly stole as much as I could for another action I made! :grin: Having working examples is gold.

**Comment by jessfraz** [comment]
is this the same as #15?

**Comment by lucas-nelson** [comment]
@jessfraz yes, yes it is. hkdobrev has described the problem more elegantly than I.

**Comment by jessfraz** [comment]
ah okay cool then I think we can close because it's fixed but let me know if otherwise

**Comment by lucas-nelson** [comment]
Agreed.
